// Mainpage for doxygen

/** @mainpage package Likelihood

 @authors James Chiang, Pat Nolan, Karl Young, and others

 @section intro Introduction

 This package implements an extended maximum likelihood (EML)
 calculation for analyzing LAT event data.

 These data are assumed to be in a format consistent with that
 produced by the Level 1 Event Data Extractor, otherwise known as U1.
 The data may alternatively have been generated by the observation
 simulator (O2).  Accordingly, use of this tool for analysis of Event
 data requires access to a complete set of accompanying spacecraft
 orbit and attitude information, obtained using the Pointing, Livetime
 History Extractor (U3) or the orbit simulator tool (O1), as well as
 access to appropriate instrument response function data (i.e.,
 CALDB).

 However, the classes and methods used here are intended to be
 sufficiently general so that any properly implemented objective
 function should be able to be analyzed with this package, whether it
 is LAT-specific or not.

 @section LatStatModel The Unbinned log-Likelihood

 For LAT event analysis, the default statistical model we assume is
 the unbinned log-likelihood:

 \f[
 \log L = \sum_j \left[\log \left(\sum_i M_i(x_j; \vec{\alpha_i})\right)\right] 
        - \sum_i \left[\int dx M_i(x; \vec{\alpha_i})\right]
 \f]

 Here \f$x_j\f$ is the \f$j\f$th photon Event, as specified by
 apparent energy, direction, and arrival time. The function \f$M_i(x;
 \vec{\alpha_i})\f$ returns the flux density in units of counts per
 energy-time-area-solid angle (i.e., photon fluxes convolved through
 the instrument response) for the \f$i\f$th Source at a point \f$x\f$
 in the Event configuration space, hereafter known as the "data
 space".  Each \f$M_i\f$ is defined, in part, by a vector of parameter
 values \f$\vec{\alpha_i}\f$; collectively, the \f$\vec{\alpha_i}\f$
 vectors form the space over which the objective function is to be
 optimized.  The integral over the data space in the second term is
 the predicted number of Events expected to be seen from Source
 \f$i\f$.

 @section classes Important Classes

 Cast in this form, the problem lends itself to being described by the
 following classes.  Some of these classes now reside in the optimizers
 and latResponse packages.

   - optimizers::Function Objects of this class act as "function
   objects" in that the function call operator () is overloaded so
   that instances behave like ordinary C functions.  Several methods
   are also provided for accessing the model Parameters and
   derivatives with respect to those Parameters, either singly or in
   groups.  The behavior of this class is greatly facilitated by the
   Parameter and Arg classes.

   - optimizers::Parameter This is essentially an n-tuple containing
   model parameter information (and access methods) comprising the
   parameter value, scale factor, name, upper and lower bounds and
   whether the parameter is to be considered free or fixed in the
   fitting process.

   - optimizers::Arg This class wraps arguments to Function objects so
   that Function's derivative passing mechanisms can be inherited by
   subclasses regardless of the actual type of the underlying
   argument.  For example, in the log-likelihood, we define
   Likelihood::logSrcModel, a Function subclass that returns the
   quantity inside the square brackets of the first term on the rhs.
   Acting as a function, logSrcModel naturally wants to take an Event
   as its argument, so we wrap an Event object with EventArg.
   Similarly, the quantity in the square brackets of the second term
   on the rhs we implement as the Likelihood::Npred class.  This class
   wants to have a Source object as its argument, which we wrap with
   the SrcArg class.

   - Likelihood::Source An abstract base class for gamma-ray sources.
   It specifies four key methods (as pure virtual functions); the
   latter two methods are wrapped by the Npred class in order to give
   them Function behavior:
      - fluxDensity(...): counts per energy-time-area-solid angle
      - fluxDensityDeriv(...): derivative wrt a Parameter
      - Npred(): predicted number of photons in the ROI
      - NpredDeriv(...): derivative of Npred wrt a Parameter

   - Likelihood::Event An n-tuple containing photon event arrival
   time, apparent energy and direction, as well as spacecraft attitude
   information at the event arrival time and event-specific response
   function data for use with components of the diffuse emission
   model.

   - latResponse::[IAeff, IPsf, IEdisp] These classes provide abstract
   interfaces to the instrument response functions comprising the
   effective area, the point-spread function, and the energy
   dispersion.  Concrete implementations exist for the Glast25
   parameterizations as well as for the EGRET response functions.

   - Likelihood::RoiCuts An n-tuple Singleton class that contains the
   "region-of-interest" cuts.  These are essentially the bounds of the
   data space as a function of arrival time, apparent energy, apparent
   direction, zenith angle, etc..

   - Likelihood::ScData A Singleton object that contains the
   spacecraft data n-tuples (ScNtuple).

   - Likelihood::SourceFactory This class provides a common access
   point for retrieving and storing Sources. Sources that have been
   constructed to comprise position and spectral information can be
   stored here, then cloned for later use.  The sources can also be
   read in from and output to an xml file.

   - optimizers::Optimizer An abstract base class for the algorithms
   which maximize the desired objective functions.  Choice of
   optimization methods are encapsulated in three sub-classes which
   simply wrap existing implementations that are/were originally
   available as Fortran code: Lbfgs, Minuit, and Drmngb.  

 <hr>
 @section notes Release Notes
  release.notes

 <hr>
 @section requirements requirements
 @verbinclude requirements

 <hr> 
 @todo Energy dispersion
 @todo Generalize Npred calculation, e.g., zenith angle cuts, fit-able 
       source locations
 @todo Refactor Statistic and FITS-related classes (Table, FitsImage, etc.)
 @todo Use more realistic response function data
 @todo Analyze EGRET data
 @todo Boost.Python
 */

/**
 @page userGuide User's Guide

 @section likeApp likelihood

 This is an FTOOLS-like interface to the Likelihood class library.
 It uses HOOPS to obtain the command-line parameters and therefore
 requires a .par file called <a href="http://glast.stanford.edu/cgi-bin/cvsweb/Likelihood/data/likelihood.par?cvsroot=CVS_SLAC">likelihood.par</a>:

@verbinclude likelihood.par

 How the lines in this file are specified is given in the <a
 href="http://isdc.unige.ch/Soft/AstroRoot/pil.ps">PIL user
 manual</a>.

 Here is a sample session in which 1000 events of simulated data,
 produced for two 3EG sources, 3C 279 and 3C 273, are analyzed:

 @verbatim
glast-guess1[jchiang] ../rh72_gcc2953/likelihood.exe
ROI cuts file [$(LIKELIHOODROOT)/xml/RoiCuts.xml] : 
Spacecraft file [virgo_scFiles] : 
Exposure file [none] : 
Response functions to use <FRONT/BACK|COMBINED> [FRONT/BACK] : 
Source model file [virgo_region.xml] : 
Event file [virgo_region_events_0000.fits] : 
Optimizer <LBFGS|MINUIT|DRMNGB> [DRMNGB] : 
Optimizer verbosity [1] : 0
Fit tolerance [0.0001] : 
Source model output file [none] : 
Use OptEM? [no] : 
flux-style output file name [flux_model.xml] : 
Creating source named 3C 279
Computing exposure at (193.98, -5.82).....................!
Creating source named 3C 273
Computing exposure at (187.25, 2.17).....................!
adding source 3C 273
adding source 3C 279
LogLike::getEvents:
Out of 1000 events in file virgo_region_events_0000.fits,
 854 were accepted, and 146 were rejected.

Drmngb return code: 3
3C 273:
Prefactor: 2.52004 +/- 0.186379
Index: -2.56014 +/- 0.0871032
Scale: 100
Npred: 227.436

3C 279:
Prefactor: 6.46561 +/- 0.298801
Index: -1.90003 +/- 0.0296193
Scale: 100
Npred: 626.56
Writing fitted model to /dev/null
Writing flux-style xml model file to flux_model.xml
glast-guess1[jchiang] 
@endverbatim

 - The <a
   href="http://glast.stanford.edu/cgi-bin/cvsweb/Likelihood/xml/RoiCuts.xml?cvsroot=CVS_SLAC">ROI
   cuts file</a> contains basic information about the extraction
   region, valid time ranges, energies, etc.:

@verbatim
<?xml version='1.0' standalone='no'?>
<!DOCTYPE Region-of-Interest SYSTEM "RoiCuts.dtd">
<Region-of-Interest title="Virgo Region">
   <timeInterval start="0"
                 stop="7"
                 unit="days"/>
   <energies emin="30." 
             emax="3.1623e5"
             unit="MeV"/>
   <acceptanceCone longitude="193.98"
                   latitude="-5.82"
                   radius="30"
                   coordsys="Celestial"/>
</Region-of-Interest>
@endverbatim

 - The Spacecraft file is either a single FITS file or a list of FITS
   files:

@verbatim
virgo_region_scData_0000.fits
virgo_region_scData_0001.fits
@endverbatim

 - If there are diffuse components in the source model, then one must
   provide an exposure map that has been computed using the @ref
   expMap application.  If the data contain only point sources, then
   the exposure map can be omitted.

 - Presently, only Front/Back and Combined response functions for the
   Glast25 parameterizations are available.

 - The Source model file contains an xml description of the various
   sources to be modeled.  Here's the source model file used in the
   above fit:

@verbatim
<source_library title="prototype sources" function_library="$(LIKELIHOODROOT)/xml/A1_Functions.xml">
  <source name="3C 279" type="PointSource">
    <spectrum type="PowerLaw">
      <parameter max="1000" min="0.001" free="1" name="Prefactor" scale="1e-09" value="1" />
      <parameter max="-1" min="-3.5" free="1" name="Index" scale="1" value="-2" />
      <parameter max="200" min="50" free="0" name="Scale" scale="1" value="100" />
    </spectrum>
    <spatialModel type="SkyDirFunction">
      <parameter max="3.40282e+38" min="-3.40282e+38" free="0" name="RA" scale="1" value="193.98" />
      <parameter max="3.40282e+38" min="-3.40282e+38" free="0" name="DEC" scale="1" value="-5.82" />
    </spatialModel>
  </source>
  <source name="3C 273" type="PointSource">
    <spectrum type="PowerLaw">
      <parameter max="1000" min="0.001" free="1" name="Prefactor" scale="1e-09" value="1" />
      <parameter max="-1" min="-3.5" free="1" name="Index" scale="1" value="-2" />
      <parameter max="200" min="50" free="0" name="Scale" scale="1" value="100" />
    </spectrum>
    <spatialModel type="SkyDirFunction">
      <parameter max="3.40282e+38" min="-3.40282e+38" free="0" name="RA" scale="1" value="187.25" />
      <parameter max="3.40282e+38" min="-3.40282e+38" free="0" name="DEC" scale="1" value="2.17" />
    </spatialModel>
  </source>
</source_library>
@endverbatim

 - The Event file also can either be a single FITS file or a list.

 - The optimizer package provides three optimizers from which to
   choose, Lbfgs, Minuit, and Drmngb.  The latter two provide error
   estimates based on the covariance matrix computed from the inverse
   Hessian.

 - After fitting, the source model can be written to an output file.
   If the same file name as the input source model file is given, then
   the file will be overwritten.

 - Likelihood::OptEM is an alternative method for performing the
   optimization using the expectation maximization method.

 - Finally, the source model can be written out as a flux-package
   style xml file that's suitable for use with either <a
   href="http://www.slac.stanford.edu/~jchiang/O2/doxy-html/">observationSim</a>
   or <a
   href="http://www.slac.stanford.edu/exp/glast/ground/software/RM/documentation/GlastRelease/GlastRelease-v3r3p7/Gleam/v5r5/">Gleam</a>.
   Here's the resulting file for the above fit:

@verbatim
<source_library title="Likelihood_model">
  <source flux="0.0105858" name="_3C_273">
    <spectrum escale="MeV">
      <particle name="gamma">
        <power_law emax="316230" emin="30" gamma="2.56014" />
      </particle>
      <celestial_dir ra="187.25" dec="2.17" />
    </spectrum>
  </source>
  <source flux="0.0212465" name="_3C_279">
    <spectrum escale="MeV">
      <particle name="gamma">
        <power_law emax="316230" emin="30" gamma="1.90003" />
      </particle>
      <celestial_dir ra="193.98" dec="-5.82" />
    </spectrum>
  </source>
  <source name="all_in_flux_model.xml">
    <nestedSource sourceRef="_3C_273" />
    <nestedSource sourceRef="_3C_279" />
  </source>
</source_library>
@endverbatim

For the flux-style sources, the name attributes cannot start with a
numeral and cannot have spaces, so underscores have been added.  As a
convenience, a single composite source is created that comprises all
of the individual sources.

 @section TsMap TsMap

In order to find sky locations of point sources, "test statistic" maps
are created.  These are computed by placing a putative point source at
each of the pixel locations in the map and then performing the fit by
maximizing the log-likelihood.  The test statistic value at that pixel
location is then given by
\f[
T_s = -2(\log L - \log L_0).
\f]

Here, \f$\log L\f$ is the maximum log-Likelihood for the fit with the
putative point source and \f$\log L_0\f$ is the log-Likelihood in the
null hypothesis, i.e., a fit to the data without the putative point
source.  Note that there will likely be other source model components,
Galactic diffuse emission, other point sources, etc., in the source
model besides the putative point source.

Here is an example session of a TsMap run:

@verbatim
glast-guess1[jchiang]../rh72_gcc2953/TsMap.exe
ROI cuts file [../xml/RoiCuts.xml] : 
Spacecraft file [../src/test/Data/diffuse_test_5_sc_0000] : 
Exposure file [../src/test/Data/exp_diffuse_test_5_new.fits] : 
Response functions to use <FRONT/BACK|COMBINED> [FRONT/BACK] : 
Source model file [../data/Virgo_region_2.xml] : 
Event file [../src/test/Data/diffuse_test_5_0000] : 
Optimizer <LBFGS|MINUIT|DRMNGB> [DRMNGB] : 
Optimizer verbosity [0] : 
Fit tolerance [0.001] : 
Coordinate system <CEL|GAL> [CEL] : 
Longitude maximum <-360 - 360> [198] : 
Longitude minmum <-360 - 360> [190] : 
Number of longitude points <2 - 200> [20] : 
Latitude maximum <-90 - 90> [-2] : 
Latitude minimum <-90 - 90> [-10] : 
Number of latitude points <2 - 200> [20] : 
TS map file name [../data/TsMap.fits] : 
Creating source named Extragalactic Diffuse Emission
Creating source named Galactic Diffuse Emission
adding source Extragalactic Diffuse Emission
adding source Galactic Diffuse Emission
LogLike::getEvents:
Out of 609 events in file ../src/test/Data/diffuse_test_5_0000,
 609 were accepted, and 0 were rejected.

Computing Event responses for the DiffuseSources............
@endverbatim

The first nine parameters are the same as for the @ref likeApp.  The new
ones describe the region of the sky to be mapped.  Here is 
an example file <a href="http://glast.stanford.edu/cgi-bin/cvsweb/Likelihood/data/TsMap.par?cvsroot=CVS_SLAC">TsMap.par</a>:

@verbinclude TsMap.par

 @section expMap expMap

This application creates an exposure map for use by the Likelihood
package.  Here's a sample session:

@verbatim
glast-guess1[jchiang] ../rh72_gcc2953/expMap.exe 
ROI cuts file [$(LIKELIHOODROOT)/xml/RoiCuts.xml] : 
Spacecraft file [$(LIKELIHOODROOT)/src/test/Data/diffuse_test_5_sc_0000] : 
Response functions to use <FRONT/BACK|COMBINED> [COMBINED] : 
Radius of the source region (in degrees) [31] : 
Number of longitude points <2 - 1000> [10] : 
Number of latitude points <2 - 1000> [10] : 
Number of energies <2 - 100> [10] : 
Exposure file [test_expMap.fits] : 
The radius of the source region, 31, should be significantly larger (say 10 deg) than the ROI radius of 30
Computing the ExposureMap....................!
@endverbatim

Note that @b expMap uses the ROI cuts file, which should be the same
one used for the source analysis by @ref likeApp.  Contrary to
this example, one should choose sufficient resolution for the map,
meaning pixels that are typically less than 0.5 degrees on a side.
Also, since the broad PSFs of the instrument can include significant
numbers of photons from sources outside of the ROI, one should choose
a source region size that is significantly larger than the ROI.

*/


